### ISSUE TITLE
Tratamento de exceção

### ISSUE THREAD

**Issue by oliveiralex** [daniellegb/trabalho_cliente_ds01#1]
Boa tarde Daniel, tudo bem?

Sou o Alexandre e estou corrigindo o seu trabalho. Seu trabalho foi aceito, parabéns! Porém, faltou fazer o tratamento de exceções para o DELETE e o PUT. Está retornando erro 500 quando é informado um id que não existe.

Abraço e bons estudos

**Comment by daniellegb** [comment]
Olá! Meu nome é Danielle. Gênero feminino. Obrigada! Abs

Em sex., 9 de abr. de 2021 às 14:19, Alexandre ***@***.***>
escreveu:

**Comment by oliveiralex** [comment]
Me desculpe o equívoco Danielle!!
